name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Har kuni tunda avtomatik ishlaydi

  workflow_dispatch: # Qo'lda ishga tushirish uchun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jurabek-2
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Snake Animation"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg"
